on: push

jobs:
  deploy-lambda:
    runs-on: linux

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: aws login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: deploy
        runs: |
          echo deployed...
          echo deployed
